version: '2'
services:
  redis:
    image: redis
    restart: always
  backend:
    restart: always
    links:
      - "mlapi:mlapi"
    depends_on:
      - mlapi
    environment:
      - DB_HOST=mongodb://docker.for.mac.localhost:27017/fashionbot
      - DB_PORT=27017
      - DB_DATABASE=fashionbot
      - TOKEN_SECRET=018c67801bbc6f65b3ef0ecd99e7c0e8
      - PASSWORD_SECRET=c0a6137c0a9b8d24da27cf972e8ddc14
      - FACEBOOK_GRAPH_HOST=https://graph.facebook.com
      - FACEBOOK_APP_ACCESS_TOKEN=1557384474356665|jJXKWOeYqEPpSYKrP8o9hqT9p-o
      - PREFIX=/api
      - CLOTHES_COLLECTION=clothes
      - USERS_COLLECTION=users
      - CLOUDINARY_USER=closetinn
      - CLOUDINARY_API_KEY=494558945392248
      - CLOUDINARY_API_SECRET=RXGDWht3A8SbwJhIyb9nO7jETXU
      - MLAPI_SERVICE_HOST=mlapi
      - MLAPI_SERVICE_PORT=80
    build: backend/.
    command: npm start
    ports:
      - '80:80'
    expose:
      - 80
    volumes:
      - ./backend/.:/opt/app
      - /opt/app/node_modules
  scrapper:
    restart: always
    environment:
      - DB_HOST=mongodb://docker.for.mac.localhost:27017/fashionbot
      - DB_PORT=27017
      - DB_DATABASE=fashionbot
      - COLLECTION_CLOTHES=clothes
      - COLLECTION_PRICE_HISTORY=clothesPriceHistory
    build: scrapper/.
    command: python main.py
    volumes:
      - ./scrapper/.:/opt/app
  cronjobs:
    restart: always
    links:
      - "mlapi:mlapi"
      - "redis:redis"
      - "backend:backend"
    environment:
      - CLOSETINN_ENV=development
      - ADMIN_EMAILS=guilherme.kodama@gmail.com,kayron.scabral@gmail.com
      - MLAPI_SERVICE_HOST=mlapi
      - MLAPI_SERVICE_PORT=80
      - BACKEND_SERVICE_HOST=backend
      - BACKEND_SERVICE_PORT=80
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
      - DB_HOST=mongodb://docker.for.mac.localhost:27017/fashionbot
      - DB_PORT=27017
      - DB_DATABASE=fashionbot
      - TYPEFORM_API=https://api.typeform.com
      - TYPEFORM_TOKEN=Bearer 5Wi7gdVxeffTeEGgpe9HQHTwsVwBTDgbU5tKWh6bzkTd
    build: cronjobs/.
    command: python main.py
    depends_on:
      - redis
      - backend
    volumes:
      - ./cronjobs/.:/opt/app
  mlapi:
    restart: always
    links:
      - "socket_server:socket_server"
      - "redis:redis"
    depends_on:
      - redis
      - socket_server
    environment:
      - SS_PRIMARY_SERVICE_HOST=socket_server
      - SS_PRIMARY_SERVICE_PORT=5000
      - SS_SLAVE_SERVICE_HOST=socket_server
      - SS_SLAVE_SERVICE_PORT=5000
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
    build: machineLearning/api/flask/.
    command: python main.py
    ports:
      - '4000:80'
    expose:
      - 4000
  socket_server:
    restart: always
    links:
      - "redis:redis"
    environment:
      - DB_HOST=mongodb://docker.for.mac.localhost:27017/fashionbot
      - DB_PORT=27017
      - DB_DATABASE=fashionbot
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
    build: machineLearning/api/socketServer/.
    command: python ./src/server.py
    ports:
      - '5000:5000'
    volumes:
      - ./machineLearning/api/socketServer/.:/opt/app
